version: 2

builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - freebsd
      - windows
    goarch:
      - amd64
      - arm64
    ignore:
      - goos: freebsd
        goarch: arm64
      - goos: windows
        goarch: arm64
    ldflags:
      - -X github.com/mostlygeek/llama-swap/version.Version={{.Version}} -X github.com/mostlygeek/llama-swap/version.Commit={{.Commit}} -X github.com/mostlygeek/llama-swap/version.Date={{.CommitDate}}

archives:
  - id: default
    formats:
      - tar.gz
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    builds_info:
      group: root
      owner: root
    format_overrides:
      # use zip format for windows
      - goos: windows
        formats:
          - zip
