version: 2

env:
  - GO111MODULE={{ if index .Env "GO111MODULE"  }}{{ .Env.GO111MODULE }}{{ else }}auto{{ end }}

builds:
  - env:
      - CGO_ENABLED=0
      - GO111MODULE={{ if index .Env "GO111MODULE"  }}{{ .Env.GO111MODULE }}{{ else }}auto{{ end }}
    goos:
      - linux
      - darwin
      - freebsd
      - windows
    goarch:
      - amd64
      - arm64
    ignore:
      - goos: freebsd
        goarch: arm64
      - goos: windows
        goarch: arm64

archives:
  - id: default
    formats:
      - tar.gz
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    builds_info:
      group: root
      owner: root
    format_overrides:
      # use zip format for windows
      - goos: windows
        formats:
          - zip
